input {
  tcp {
    port => 15044
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "system" => "agent-group"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "agent-group-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
